<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\PostImage;

class CreatePostImagesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        {
            $postImages = [
                [
                   'post_id'=>1,
                   'post_image_path'=>'https://picsum.photos/1920/1080?random=1',
                   'post_image_caption'=>'title',
                ],
                [
                    'post_id'=>2,
                    'post_image_path'=>'https://picsum.photos/1920/1080?random=2',
                    'post_image_caption'=>'title',
                 ],
                 [
                    'post_id'=>3,
                    'post_image_path'=>'https://picsum.photos/1920/1080?random=3',
                    'post_image_caption'=>'title',
                 ],
                 [
                    'post_id'=>4,
                    'post_image_path'=>'https://picsum.photos/1920/1080?random=4',
                    'post_image_caption'=>'title',
                 ],
                 [
                    'post_id'=>5,
                    'post_image_path'=>'https://picsum.photos/1920/1080?random=5',
                    'post_image_caption'=>'title',
                 ],
                 [
                    'post_id'=>6,
                    'post_image_path'=>'https://picsum.photos/1920/1080?random=6',
                    'post_image_caption'=>'title',
                 ],
                 [
                    'post_id'=>7,
                    'post_image_path'=>'https://picsum.photos/1920/1080?random=7',
                    'post_image_caption'=>'title',
                 ],
                 [
                    'post_id'=>8,
                    'post_image_path'=>'https://picsum.photos/1920/1080?random=8',
                    'post_image_caption'=>'title',
                 ],
                 [
                    'post_id'=>9,
                    'post_image_path'=>'https://picsum.photos/1920/1080?random=9',
                    'post_image_caption'=>'title',
                 ],
                 [
                    'post_id'=>10,
                    'post_image_path'=>'https://picsum.photos/1920/1080?random=10',
                    'post_image_caption'=>'title',
                 ],
                 [
                    'post_id'=>11,
                    'post_image_path'=>'https://picsum.photos/1920/1080?random=11',
                    'post_image_caption'=>'title',
                 ],
                 [
                    'post_id'=>12,
                    'post_image_path'=>'https://picsum.photos/1920/1080?random=12',
                    'post_image_caption'=>'title',
                 ],
                 [
                    'post_id'=>13,
                    'post_image_path'=>'https://picsum.photos/1920/1080?random=13',
                    'post_image_caption'=>'title',
                 ],
                 [
                    'post_id'=>14,
                    'post_image_path'=>'https://picsum.photos/1920/1080?random=14',
                    'post_image_caption'=>'title',
                 ],
                 [
                    'post_id'=>15,
                    'post_image_path'=>'https://picsum.photos/1920/1080?random=15',
                    'post_image_caption'=>'title',
                 ],
                 [
                    'post_id'=>16,
                    'post_image_path'=>'https://picsum.photos/1920/1080?random=16',
                    'post_image_caption'=>'title',
                 ],
                 [
                    'post_id'=>17,
                    'post_image_path'=>'https://picsum.photos/1920/1080?random=17',
                    'post_image_caption'=>'title',
                 ],
                 [
                    'post_id'=>18,
                    'post_image_path'=>'https://picsum.photos/1920/1080?random=18',
                    'post_image_caption'=>'title',
                 ],
                 [
                    'post_id'=>19,
                    'post_image_path'=>'https://picsum.photos/1920/1080?random=19',
                    'post_image_caption'=>'title',
                 ],
                 [
                    'post_id'=>20,
                    'post_image_path'=>'https://picsum.photos/1920/1080?random=20',
                    'post_image_caption'=>'title',
                 ],
                 [
                    'post_id'=>21,
                    'post_image_path'=>'https://picsum.photos/1920/1080?random=21',
                    'post_image_caption'=>'title',
                 ],
                 [
                    'post_id'=>22,
                    'post_image_path'=>'https://picsum.photos/1920/1080?random=22',
                    'post_image_caption'=>'title',
                 ],
                 [
                    'post_id'=>23,
                    'post_image_path'=>'https://picsum.photos/1920/1080?random=23',
                    'post_image_caption'=>'title',
                 ],
                 [
                    'post_id'=>24,
                    'post_image_path'=>'https://picsum.photos/1920/1080?random=24',
                    'post_image_caption'=>'title',
                 ],
                 [
                    'post_id'=>25,
                    'post_image_path'=>'https://picsum.photos/1920/1080?random=25',
                    'post_image_caption'=>'title',
                 ],
                 [
                    'post_id'=>26,
                    'post_image_path'=>'https://picsum.photos/1920/1080?random=26',
                    'post_image_caption'=>'title',
                 ],
            ];
        
            foreach ($postImages as $key => $postImage) {
                PostImage::create($postImage);
            }
        }
    }
}
